# Generated by Django 3.1.3 on 2021-04-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
